# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robbie/workspace/media/meida/media

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robbie/workspace/media/meida/media

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robbie/workspace/media/meida/media/CMakeFiles /home/robbie/workspace/media/meida/media/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robbie/workspace/media/meida/media/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named media

# Build rule for target.
media: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 media
.PHONY : media

# fast build rule for target.
media/fast:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/build
.PHONY : media/fast

#=============================================================================
# Target rules for targets named buildice

# Build rule for target.
buildice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 buildice
.PHONY : buildice

# fast build rule for target.
buildice/fast:
	$(MAKE) -f CMakeFiles/buildice.dir/build.make CMakeFiles/buildice.dir/build
.PHONY : buildice/fast

src/buffer.o: src/buffer.cpp.o

.PHONY : src/buffer.o

# target to build an object file
src/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/buffer.cpp.o
.PHONY : src/buffer.cpp.o

src/buffer.i: src/buffer.cpp.i

.PHONY : src/buffer.i

# target to preprocess a source file
src/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/buffer.cpp.i
.PHONY : src/buffer.cpp.i

src/buffer.s: src/buffer.cpp.s

.PHONY : src/buffer.s

# target to generate assembly for a file
src/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/buffer.cpp.s
.PHONY : src/buffer.cpp.s

src/hkdevice/hikcontroller.o: src/hkdevice/hikcontroller.cpp.o

.PHONY : src/hkdevice/hikcontroller.o

# target to build an object file
src/hkdevice/hikcontroller.cpp.o:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/hkdevice/hikcontroller.cpp.o
.PHONY : src/hkdevice/hikcontroller.cpp.o

src/hkdevice/hikcontroller.i: src/hkdevice/hikcontroller.cpp.i

.PHONY : src/hkdevice/hikcontroller.i

# target to preprocess a source file
src/hkdevice/hikcontroller.cpp.i:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/hkdevice/hikcontroller.cpp.i
.PHONY : src/hkdevice/hikcontroller.cpp.i

src/hkdevice/hikcontroller.s: src/hkdevice/hikcontroller.cpp.s

.PHONY : src/hkdevice/hikcontroller.s

# target to generate assembly for a file
src/hkdevice/hikcontroller.cpp.s:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/hkdevice/hikcontroller.cpp.s
.PHONY : src/hkdevice/hikcontroller.cpp.s

src/hkdevice/sdkuser.o: src/hkdevice/sdkuser.cpp.o

.PHONY : src/hkdevice/sdkuser.o

# target to build an object file
src/hkdevice/sdkuser.cpp.o:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/hkdevice/sdkuser.cpp.o
.PHONY : src/hkdevice/sdkuser.cpp.o

src/hkdevice/sdkuser.i: src/hkdevice/sdkuser.cpp.i

.PHONY : src/hkdevice/sdkuser.i

# target to preprocess a source file
src/hkdevice/sdkuser.cpp.i:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/hkdevice/sdkuser.cpp.i
.PHONY : src/hkdevice/sdkuser.cpp.i

src/hkdevice/sdkuser.s: src/hkdevice/sdkuser.cpp.s

.PHONY : src/hkdevice/sdkuser.s

# target to generate assembly for a file
src/hkdevice/sdkuser.cpp.s:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/hkdevice/sdkuser.cpp.s
.PHONY : src/hkdevice/sdkuser.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/media.o: src/media.cpp.o

.PHONY : src/media.o

# target to build an object file
src/media.cpp.o:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/media.cpp.o
.PHONY : src/media.cpp.o

src/media.i: src/media.cpp.i

.PHONY : src/media.i

# target to preprocess a source file
src/media.cpp.i:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/media.cpp.i
.PHONY : src/media.cpp.i

src/media.s: src/media.cpp.s

.PHONY : src/media.s

# target to generate assembly for a file
src/media.cpp.s:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/media.cpp.s
.PHONY : src/media.cpp.s

src/mediastream.o: src/mediastream.cpp.o

.PHONY : src/mediastream.o

# target to build an object file
src/mediastream.cpp.o:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/mediastream.cpp.o
.PHONY : src/mediastream.cpp.o

src/mediastream.i: src/mediastream.cpp.i

.PHONY : src/mediastream.i

# target to preprocess a source file
src/mediastream.cpp.i:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/mediastream.cpp.i
.PHONY : src/mediastream.cpp.i

src/mediastream.s: src/mediastream.cpp.s

.PHONY : src/mediastream.s

# target to generate assembly for a file
src/mediastream.cpp.s:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/mediastream.cpp.s
.PHONY : src/mediastream.cpp.s

src/rtpsender.o: src/rtpsender.cpp.o

.PHONY : src/rtpsender.o

# target to build an object file
src/rtpsender.cpp.o:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/rtpsender.cpp.o
.PHONY : src/rtpsender.cpp.o

src/rtpsender.i: src/rtpsender.cpp.i

.PHONY : src/rtpsender.i

# target to preprocess a source file
src/rtpsender.cpp.i:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/rtpsender.cpp.i
.PHONY : src/rtpsender.cpp.i

src/rtpsender.s: src/rtpsender.cpp.s

.PHONY : src/rtpsender.s

# target to generate assembly for a file
src/rtpsender.cpp.s:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/rtpsender.cpp.s
.PHONY : src/rtpsender.cpp.s

src/stream.o: src/stream.cpp.o

.PHONY : src/stream.o

# target to build an object file
src/stream.cpp.o:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/stream.cpp.o
.PHONY : src/stream.cpp.o

src/stream.i: src/stream.cpp.i

.PHONY : src/stream.i

# target to preprocess a source file
src/stream.cpp.i:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/stream.cpp.i
.PHONY : src/stream.cpp.i

src/stream.s: src/stream.cpp.s

.PHONY : src/stream.s

# target to generate assembly for a file
src/stream.cpp.s:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/stream.cpp.s
.PHONY : src/stream.cpp.s

src/streamI.o: src/streamI.cpp.o

.PHONY : src/streamI.o

# target to build an object file
src/streamI.cpp.o:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/streamI.cpp.o
.PHONY : src/streamI.cpp.o

src/streamI.i: src/streamI.cpp.i

.PHONY : src/streamI.i

# target to preprocess a source file
src/streamI.cpp.i:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/streamI.cpp.i
.PHONY : src/streamI.cpp.i

src/streamI.s: src/streamI.cpp.s

.PHONY : src/streamI.s

# target to generate assembly for a file
src/streamI.cpp.s:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/streamI.cpp.s
.PHONY : src/streamI.cpp.s

src/streammanager.o: src/streammanager.cpp.o

.PHONY : src/streammanager.o

# target to build an object file
src/streammanager.cpp.o:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/streammanager.cpp.o
.PHONY : src/streammanager.cpp.o

src/streammanager.i: src/streammanager.cpp.i

.PHONY : src/streammanager.i

# target to preprocess a source file
src/streammanager.cpp.i:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/streammanager.cpp.i
.PHONY : src/streammanager.cpp.i

src/streammanager.s: src/streammanager.cpp.s

.PHONY : src/streammanager.s

# target to generate assembly for a file
src/streammanager.cpp.s:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/streammanager.cpp.s
.PHONY : src/streammanager.cpp.s

src/zmd5.o: src/zmd5.c.o

.PHONY : src/zmd5.o

# target to build an object file
src/zmd5.c.o:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/zmd5.c.o
.PHONY : src/zmd5.c.o

src/zmd5.i: src/zmd5.c.i

.PHONY : src/zmd5.i

# target to preprocess a source file
src/zmd5.c.i:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/zmd5.c.i
.PHONY : src/zmd5.c.i

src/zmd5.s: src/zmd5.c.s

.PHONY : src/zmd5.s

# target to generate assembly for a file
src/zmd5.c.s:
	$(MAKE) -f CMakeFiles/media.dir/build.make CMakeFiles/media.dir/src/zmd5.c.s
.PHONY : src/zmd5.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... media"
	@echo "... buildice"
	@echo "... src/buffer.o"
	@echo "... src/buffer.i"
	@echo "... src/buffer.s"
	@echo "... src/hkdevice/hikcontroller.o"
	@echo "... src/hkdevice/hikcontroller.i"
	@echo "... src/hkdevice/hikcontroller.s"
	@echo "... src/hkdevice/sdkuser.o"
	@echo "... src/hkdevice/sdkuser.i"
	@echo "... src/hkdevice/sdkuser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/media.o"
	@echo "... src/media.i"
	@echo "... src/media.s"
	@echo "... src/mediastream.o"
	@echo "... src/mediastream.i"
	@echo "... src/mediastream.s"
	@echo "... src/rtpsender.o"
	@echo "... src/rtpsender.i"
	@echo "... src/rtpsender.s"
	@echo "... src/stream.o"
	@echo "... src/stream.i"
	@echo "... src/stream.s"
	@echo "... src/streamI.o"
	@echo "... src/streamI.i"
	@echo "... src/streamI.s"
	@echo "... src/streammanager.o"
	@echo "... src/streammanager.i"
	@echo "... src/streammanager.s"
	@echo "... src/zmd5.o"
	@echo "... src/zmd5.i"
	@echo "... src/zmd5.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

